# https://domluna.github.io/JuliaFormatter.jl/stable/

indent = 4
margin = 92

always_use_return = false
always_for_in = false
import_to_using = true

whitespace_in_kwargs = true
whitespace_typedefs = true
whitespace_ops_in_indices = true

annotate_untyped_fields_with_any = true
trailing_comma = true
align_assignment = false
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
